### ISSUE TITLE
지킬 빌드 에러

### ISSUE THREAD

**Issue by wagurano** [rorlakr/railsgirls#5]
2017년 6월 번역 내용을 gh-pages 브랜치에 반영하였으나 빌드 에러 발생하여 확인하고 있습니다.

**Comment by wagurano** [comment]
baseurl 사용하고 최근 수정분 반영함
https://github.com/rorlakr/railsgirls/commit/c95827265b9e390ffb8ce40c9aa9c748fa1eae4f

**Comment by corazzon** [comment]
감사합니다 👍
