### ISSUE TITLE
번역자 표시 방법

### ISSUE THREAD

**Issue by wagurano** [rorlakr/railsgirls#7]
위치 

1. 원저자와 같은 줄에 표시
1. 원저자의 바로 밑줄에 표시
1. 기타 의견

링크

1. 개인 블로그 링크
1. 깃헙 핸들 링크
1. 기타 의견

**Comment by corazzon** [comment]
처음엔 원저작자 밑줄에 표시를 했는데 일본 번역을 보니 원저작자와 같은 줄에 표시되어 있어 오늘 PR에 올린 번역은 원저작와 같은 줄에 표시했습니다. diff를 볼 때도 2번보다는 1번이 변경사항이 적어 1번으로 표시했으면 합니다.

위치 1. 원저자와 같은 줄에 표시
링크 3. 개인이 원하는 링크로 했으면 합니다.

**Comment by wagurano** [comment]
위치는 1안으로 원저자와 번역자를 같은 줄로 표시하면서, 여기에 덧붙여서 원문과 한국어로 번역한 파일의 전체 라인 길이를 똑같이 맞추면 좋겠습니다.

전체 라인 길이를 똑같이 맞추면, 원문에 있는 줄과 한국어 번역도 같은 줄에 있어서, 나중에 원문을 수정하였을 때 추적하기 쉽겠다는 생각이 들었습니다.
원문은 한줄인데, 한국어로는 두줄로 해야 하거나, 원문은 두줄이나, 한국어로는 한줄일 때는 좀 더 생각해봐야겠군요.

네, 링크는 3안으로 개인 원하는 링크로 정하겠습니다. 깃헙 핸들은 커밋로그 보면 알 수 있으니까 개인 블로그를 넣어보면 어떨까하고 생각했습니다.

**Comment by corazzon** [comment]
네, 변경사항을 추적하다보면 저도 원문과 길이는 맞추는 게 좋겠다는 생각이 듭니다. 다만 부득이하게 줄어들거나 늘어나게 될 때도 고민이 필요할 듯 합니다.

**Comment by wagurano** [comment]
[위키 레일스 걸스 번역 참고](https://github.com/rorlakr/railsgirls/wiki)에 반영함
